### ISSUE TITLE
[FDroid] Failing build / play-services

### ISSUE THREAD

**Issue by krt16s** [TomasValenta/WebCamViewer#25]
The reason for the failing build is that you included a non-free dependency, namely Google's play-services, that we cannot build. Maybe provide two gradle build flavors, with one targeting a fully free build?

**Comment by TomasValenta** [comment]
Yes,
I added support for showing WebCams on Google Maps and importing WebCams from nearby distance, then I need play-services-maps and play-services-location. When I create two gradle build flavors, how building will work? Can you show me a example?
Its like this? http://developer.android.com/tools/building/configuring-gradle.html#workBuildVariants
This will create two completely different applications, there is no other option? I think, it's crazy for the future development or not?

**Comment by TomasValenta** [comment]
Maybe now it's better for me thinking about maps sdk replacement, for example to oss Mapbox and getting location through LocationManager instead with play services location...

**Comment by TomasValenta** [comment]
Ok @krt16s,
I have removed non-free dependency and replaced it with Mapbox. It's now possible to update the F-Droid repo?

**Comment by krt16s** [comment]
Yes, works fine. Thanks for the quick response. I know play-services are very tempting for developers and removing it can be quite a pain in the ass. So thanks again for staying free ;)

**Comment by TomasValenta** [comment]
Thank you to,
you're right ;) Now are the Google maps better than others, but I would like keep complete code open source. And maps are not so important part of this project ;)

**Comment by ejabbsrh** [comment]
Yes, thank you for choosing OpenStreetMap over Google!

**Comment by TomasValenta** [comment]
Hi Boris,
I'm looking to F-Droid page now and still no updates? It's there another problem with building?

**Comment by krt16s** [comment]
2.1.1 is published, see https://f-droid.org/repository/browse/?fdfilter=webcam&fdid=cz.yetanotherview.webcamviewer.app . Building can take up to 24hrs, depending on what is queued up. E.g. If we build Firefox we are talking about 9 hours per arch, so 18 hrs in total. I think VLC was in the queue for tonight, which takes quite some time. So this might be the delay reason.

**Comment by TomasValenta** [comment]
I understand and you're right, now it's published, thank you again ;)

**Comment by TomasValenta** [comment]
Hello Boris,

I want to ask you about [libVLC](https://wiki.videolan.org/AndroidCompile/). It's this problem for F-Droid repo to build WebCam Viewer when I put this compiled binary to my project?

**Comment by krt16s** [comment]
We'd need to replace the lib. We build VLC, so it should be doable. However, I most likely wont have the time for it in the next two weeks since Osmand2 and LibreOfficeViewer are begging for an update :P

**Comment by TomasValenta** [comment]
Today I created the library on Bintray and add it to Gradle. So I think, thats can be ok?
https://bintray.com/tomasvalenta/maven/libVLC-android/

**Comment by krt16s** [comment]
Currently central and jcenter are allowed. While jcenter is hosted on bintray, other bintray repos are not. If you compiled the lib yourself, could you just provide the build recipe? I will try to wrap fdroid's syntactic sugar  around it and set your app up to use it. As I said, I cannot tell if I manage to do it in the next days...

**Comment by TomasValenta** [comment]
Thanks, that would be nice ;) It's not important now, I released the first beta, I think final version come in 10 days maybe. What you mean "build recipe" ? I use this how to:
https://wiki.videolan.org/AndroidCompile/
and at the end this commands:
> sh compile.sh -a armeabi-v7a release
> sh compile-libvlc.sh -a armeabi-v7a release

the the build script create aar file in this directory:
> ../android/libvlc/build/outputs/aar

and I put it on bintray and include to gradle:
> https://github.com/TomasValenta/WebCamViewer/blob/master/build.gradle#L19
> https://github.com/TomasValenta/WebCamViewer/blob/master/app/build.gradle#L32

**Comment by TomasValenta** [comment]
And I forgot for one thing, I don't use latest development, but tag to stable release, so after:
> git clone git://git.videolan.org/vlc-ports/android.git

I use:
> git checkout [stable release tag]

from this page http://git.videolan.org/?p=vlc-ports/android.git;a=summary. For example:
> git checkout 8ebcc4b79a3dccd3cf79ffd205ac94d237b49fb5

**Comment by TomasValenta** [comment]
Hello Boris,

yesterday I released new version. Can you check if the build has failed on F-Droid (the libVLC dependency) or has not started  yet?

**Comment by krt16s** [comment]
Sorry, forgot about you and the VLClib in the first place and was away last week. I hope I can look into this the next couple of days.

**Comment by TomasValenta** [comment]
Thank you Boris!

**Comment by krt16s** [comment]
I tried to build the lib and failed. It looks like the same issues, that prevent VLC 1.4.1 and 1.4.99 to be in F-Droid by now. I will try to step through the changes between 140 and 141.

I'll keep you posted.

**Comment by TomasValenta** [comment]
Hello,
I am now on holiday, but look to this thread for more informationv about failed build:
https://forum.videolan.org/viewtopic.php?f=35&t=126228

**Comment by TomasValenta** [comment]
Any news?

**Comment by krt16s** [comment]
i have it compiling on my machine, but i currently try to get in contact with the admin of our build server, to get the exact version we use and the possibility to upgrade, so we don't have to mess with the build recipe.

**Comment by TomasValenta** [comment]
Ok,
I understand. Yesterday I have compiled new libVLC 3.0.0 and adapt my code to work with it. So please focus on this new version, instead of 1.4.1 or 1.4.99.
Thank you

**Comment by TomasValenta** [comment]
Hello Boris,

I need to make some changes to database access and the not updated version app on F-Droid brings me some problems. So it's possible update the app in F-Droid repository or can you delete it?

**Comment by krt16s** [comment]
As I said, I am currently waiting for fdroidserver changes to happen :/. I can move the app to the archive, and re-enable it when the new build is ready. However, current users will not be affected by this (we cannot force removal apps from users ;) )

**Comment by TomasValenta** [comment]
I understand,
but we waiting for this more than one month ;)
Ok, keep it online on F-Droid, but please try to fix the problem on build server as soon as possible. I need to make some restriction, because some people stealing my work and accessing the database from the stolen source code. Thank you ;)

**Comment by krt16s** [comment]
It looks like VLC1.4.1 is building now, issue a 1.5.1.1 build. If that succeeds I will try to fix up your build. Which commit do you use for your libvlc?

**Comment by TomasValenta** [comment]
Nice, thank you ;) I use 1.5.1.1 commit, so:
8ccfaad4341b09afd95910e6eff083e1621fa6dc

**Comment by krt16s** [comment]
1.5.1.1 is built, but I having trouble building the lib as part of your app, since fdroid has problems with multiple gradle calls. For now I enabled 3.0.4 with binaries from your repo and added a note that binaries are used to the description. Feel free to to do your database update and push the new version. Hopefully I have libvlc fixed up by then, otherwise I will greenlight it again. Sorry for the inconveniences.

**Comment by TomasValenta** [comment]
Ok,
thank you Boris!

**Comment by TomasValenta** [comment]
I released a new version, it's needed to be updated manually on F-Droid?

**Comment by krt16s** [comment]
Yes, for several reasons: first, I disable auto updates on apps with binaries in general, second fdroidserver is lacking the capability to auto-update apps with abisplits, it only tracks the highest versioncode (x86) and would only update this flavour. I rather have it notify me about changes and then deploy all abi flavours at the same time.

**Comment by TomasValenta** [comment]
Ok,

I understand. Thank you Boris ;)

**Comment by TomasValenta** [comment]
Bump, new version ;)
