### ISSUE TITLE
Leave previous image during update

### ISSUE THREAD

**Issue by blaueente** [TomasValenta/WebCamViewer#27]
Currently when I hit update, the image is replaced by a grey frame with a rotating circle, until the new image has been loaded. It would be much nicer if the new image would immediately replace the old one. This would also make it easier to spot differences.

**Comment by TomasValenta** [comment]
Hello,

Thank you for the suggestion. You mean the list of WebCams refresh or single WebCam refresh?

**Comment by TomasValenta** [comment]
This enhancement was added to single full screen view.
