### ISSUE TITLE
Protocol family unavailable

### ISSUE THREAD

**Issue by makbn** [TomasValenta/WebCamViewer#45]
Gradle sync failed: Protocol family unavailable
this error drives me crazy!how can i fix this?

**Comment by TomasValenta** [comment]
Sorry,

but I think, the problem must be on your side, because I try it now in VirtualBox on clean Ubuntu installation with latest Android Studio 1.3.1 and compilation was simply successful.

Do you use: in Android Studio -> Import project (Eclipse, Gradle, etc..) ?

**Comment by makbn** [comment]
i know its on my side :D im beginner 
i fixed it by setting Gradle dir manually but next problem is dependencies!! cant resolve symbol ...

**Comment by TomasValenta** [comment]
Simple "HOW-TO" for you:
1. Download this archive: https://github.com/TomasValenta/WebCamViewer/archive/master.zip or use git to clone.
2. Extract the archive.
3. Open Android Studio -> **Import project (Eclipse, Gradle, etc..)** (Not open!)
4. That's all, nothing more is needed. Gradle do everything for you!

Btw, why do you want to compile my project source code? Do you want to improve or fix code and then send me the patch? This source code is public and open, but is copyrighted to me, so please read first the license rules!

**Comment by makbn** [comment]
no i want just learn sth from your code bro thank you

**Comment by TomasValenta** [comment]
Does it work now?

**Comment by makbn** [comment]
no i updated my sdk and android studio last night and now i cant do any thing !!i get " Protocol family unavailable" error again for my own projects !!idk what should ido!!
i googled this but nothing found
(sorry for my bad english)

**Comment by TomasValenta** [comment]
So,
uninstall Android Studio and delete all related files. You are on Windows, Linux or OSX?
https://www.google.cz/#safe=off&q=How+to+completely+uninstall+android+studio
then download stable version from
https://developer.android.com/sdk/index.html
and start again...

**Comment by makbn** [comment]
im on windows thank you bro  ill do it

**Comment by makbn** [comment]
new error :(
Error:(17, 0) Could not find property 'MATERIAL_KEYSTORE_FILE' on SigningConfig_Decorated{name=release, storeFile=null, storePassword=null, keyAlias=null, keyPassword=null, storeType=null}.

**Comment by makbn** [comment]
finally i do it :dancer: thank you and sorry for spam :D

**Comment by TomasValenta** [comment]
You are welcome ;)
